### ISSUE TITLE
russian characters codepage issue

### ISSUE THREAD

**Issue by amzamzamzamz** [msagca/qbittorrent-plugins#2]
There are problem with russian characters codepage.
For example...
Search string: "чебурашка"
web:
![1](https://user-images.githubusercontent.com/43040644/216807397-fd18822b-80d6-4e45-930d-5ba4a36d441b.jpg)
qbittorrent:

![2](https://user-images.githubusercontent.com/43040644/216807405-16570991-551b-4722-933a-6394e3d0a69d.jpg)

**Comment by msagca** [comment]
Hi @amzamzamzamz 

The problem is that the [retrieve_url](https://github.com/qbittorrent/qBittorrent/blob/master/src/searchengine/nova3/helpers.py#L73) function cannot correctly decode the retrieved data. It's not something that I can fix.
