### ISSUE TITLE
Recently stopped working

### ISSUE THREAD

**Issue by gohilo** [msagca/qbittorrent-plugins#3]
This used to work well but very recently has stopped working at all.

I'm not very techy but I have noticed that the website now shows a warning page when first accessed and then again from time to time when searching. I have attached an image.

Just a guess but perhaps this is now throwing out the plugin search from working.

![securitywarning](https://user-images.githubusercontent.com/66495024/222970773-74072568-c959-4df2-86a6-a886229b52f4.jpg)

Wish I could help fix it but my python skills are very very limited and my web skills even more limited.

Hope you can fix.

**Comment by msagca** [comment]
Hi @gohilo 

Sorry to hear that but I don't think there is anything I can do about this issue. All my code does is walk through the parsed HTML and get information about the torrents on the page. HTMLParser is responsible for retrieving the page and if it fails to do so my plugin will also fail.

**Comment by gohilo** [comment]
Ok. Many thanks for the prompt reply and letting me know.
